drop table quotes if exists
drop table categories if exists
drop table projects if exists
drop table comments if exists
drop table users if exists

CREATE TABLE quotes (id bigint generated by default as identity (start with 1), primary key (id), text varchar(255), author varchar(255))
CREATE TABLE categories (id bigint generated by default as identity (start with 1), primary key (id), name varchar(255))
CREATE TABLE projects (id bigint generated by default as identity (start with 1), primary key (id), name varchar(255), category_id BIGINT, theEndDay integer, link varchar(255), description varchar(255), short_description varchar(255), history varchar(255), pledged double, goal double, status integer )
create table comments (id bigint generated by default as identity (start with 1), primary key (id), text varchar(255), status integer, project_id BIGINT, user_id BIGINT) 
create table users (id bigint generated by default as identity (start with 1), primary key (id), login varchar(255), password varchar(255))